# Model & dataset
pretrained_model_name_or_path: "/remote-home1/lzjjin/.cache/modelscope/hub/models/AI-ModelScope/stable-diffusion-v1-5"
revision: null
variant: null
dataset_name: null
#dataset_name: "lambdalabs/naruto-blip-captions"
dataset_config_name: null
train_data_dir: "phiyodr/coco2017"
cache_dir: null
image_column: "image_path"
caption_column: "captions"
max_train_samples: null

# Training hyperparameters
train_batch_size: 6
num_train_epochs: 10
max_train_steps: 30000
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
lr_scheduler: "constant"
lr_warmup_steps: 500
gradient_checkpointing: false
mixed_precision: "fp16"
report_to: "tensorboard"
seed: 42
add_loss_mse: true
loss_mse_lambda: 0.5
loss_nll_lambda: 1.0
nll_lambda_mse: 1.0
# Image preprocessing & validation
resolution: 512
center_crop: false
random_flip: true
validation_prompts:
  - "A hyper-realistic photo of a cute cat."
  - "A fantasy landscape with floating islands at sunset"
  - "A cyberpunk city street at night, neon lights reflecting on wet pavement"
  - "A watercolor painting of a tranquil Japanese garden in spring"
  - "A 3D render of a futuristic sports car racing through a desert canyon"
  - "An oil painting of an old wizard studying ancient tomes by candlelight"
validation_steps: 300
log_posterior_interval: 500
# Output & logging
output_dir: "flow-model-finetuned-coco"
logging_dir: "logs"
push_to_hub: false
hub_token: null
hub_model_id: null
tracker_project_name: "flow-fine-tune"

# Optimizer settings
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-8
max_grad_norm: 1.0

# Diffusers-specific options
input_perturbation: 0.0
noise_offset: 0.0
snr_gamma: null
dream_training: false
dream_detail_preservation: 1.0
use_8bit_adam: false
use_ema: false
offload_ema: false
foreach_ema: false
non_ema_revision: null
enable_xformers_memory_efficient_attention: false

# DataLoader & checkpointing
dataloader_num_workers: 0
checkpointing_steps: 500
checkpoints_total_limit: 5
resume_from_checkpoint: null

# Performance tweaks
allow_tf32: false
scale_lr: false
prediction_type: "v_prediction"
